CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(255) NOT NULL,
    uri       VARCHAR(255) NOT NULL,
    ip        VARCHAR(45)  NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_endpoint_hits_composite
    ON endpoint_hits (app, uri, timestamp);

CREATE INDEX IF NOT EXISTS idx_endpoint_hits_unique_ip
    ON endpoint_hits (app, uri, ip)
    WHERE ip IS NOT NULL;